import type { Metadata } from 'next'
import AppShell from './components/AppShell'
import { Oswald, Lora } from 'next/font/google'
import AuthProviderWrapper from '@/components/providers/AuthProviderWrapper'
import { CartProvider } from '@/context/CartContext'
import { FavoritesProvider } from '@/context/FavoritesContext'
import './globals.css'

// Configuramos fuentes y sus variables CSS
const oswald = Oswald({
  subsets: ['latin'],
  variable: '--font-oswald', // Nombre de la variable CSS para la fuente
  display: 'swap',
})
const lora = Lora({
  subsets: ['latin'],
  variable: '--font-lora', // Nombre de la variable CSS para esta fuente
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Relojes BV Beni',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="es" className={`${oswald.variable} ${lora.variable}`}>
      <head>
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
      </head>
      <body className="bg-white flex flex-col min-h-screen">
        <AuthProviderWrapper>
          <CartProvider>
            <FavoritesProvider>
              <AppShell>{children}</AppShell>
            </FavoritesProvider>
          </CartProvider>
        </AuthProviderWrapper>
      </body>
    </html>
  )
}
