/**
 * useCreateOrder — Sprint 5 UPSERT rewire (tasks 3.1/3.2).
 *
 * Covers spec `checkout-order-upsert` (obs #1791) scenarios S3.1–S3.6 and the
 * hook-level slice of `checkout-error-display` S-MOD.6 (obs #1792).
 * Design refs: A-4 (X-Trace-Id per attempt), A-7 (NO client-side retry —
 * bounded retry lives in the backend service, obs #1783), A-9 (Spanish copy
 * via `checkoutOrderErrors`), A-12 (wire body = D-lock subset + `userId`
 * from `useAuth().user.id`; `user === null` → friendly fallback, no fetch).
 *
 * Per obs #1797 warning #2, every failure case stubs a CONCRETE status
 * literal (400/403/409/500/502) — never the widened union type.
 */
import { describe, it, expect, vi, beforeEach } from 'vitest'
import { renderHook, act } from '@testing-library/react'
import type { PaymentIntent } from '@stripe/stripe-js'
import type { CartItem } from '@/types'

// Hoisted: AuthContext state is mutable so each test drives A-12 composition.
const { mockAssembleOrderData, mockAuthState, mockPush } = vi.hoisted(() => ({
  mockAssembleOrderData: vi.fn(),
  mockAuthState: {
    user: null as { id: number; username: string; email: string } | null,
  },
  mockPush: vi.fn(),
}))

vi.mock('@/features/checkout/services/assembleOrderData', () => ({
  assembleOrderData: mockAssembleOrderData,
}))

// R-8: the hook gains an AuthContext dependency (A-12 userId composition).
vi.mock('@/context/AuthContext', () => ({
  useAuth: () => ({
    user: mockAuthState.user,
    isLoading: false,
    login: vi.fn(),
    logout: vi.fn(),
    register: vi.fn(),
  }),
}))

vi.mock('next/navigation', () => ({
  useRouter: () => ({
    push: mockPush,
    replace: vi.fn(),
    back: vi.fn(),
    forward: vi.fn(),
    refresh: vi.fn(),
    prefetch: vi.fn(),
  }),
}))

// import after mocks
import { useCreateOrder } from '../useCreateOrder'
import { checkoutOrderErrors } from '@/features/checkout/utils/checkoutOrderErrors'
import { makeCartItem } from '@/__tests__/__fixtures__/cartItem'
import { MOCK_AUTH_USER, makeAuthUser } from '@/__tests__/__fixtures__/auth'
import {
  mockUpsertResponse,
  makeUpsertSuccessEnvelope,
  makeUpsertErrorEnvelope,
  MOCK_TRACE_ID,
  UPSERT_ERROR_400_ITEMS,
  UPSERT_ERROR_403_OWNERSHIP,
  UPSERT_ERROR_409_GENERIC,
} from '@/__tests__/__fixtures__/orderPayload'

// UUIDv4 shape generated by newTraceId (A-4).
const UUID_V4 =
  /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i

const cartItem: CartItem = makeCartItem({ price: 100, quantity: 1 })
const cartItems: CartItem[] = [cartItem]
const paymentIntent = {
  id: 'pi_test_123',
  status: 'succeeded',
} as unknown as PaymentIntent

// subtotal 100 ≥ FREE_SHIPPING_THRESHOLD (50) → shipping 0.
const EXPECTED_SUBTOTAL = 100
const EXPECTED_SHIPPING = 0
const EXPECTED_PAYMENT_INFO = { method: 'card', brand: 'visa', last4: '4242' }

function fetchMock(): ReturnType<typeof vi.fn> {
  return global.fetch as unknown as ReturnType<typeof vi.fn>
}

function lastFetchCall(fetch: ReturnType<typeof vi.fn>) {
  const call = fetch.mock.calls[fetch.mock.calls.length - 1]
  expect(call).toBeDefined()
  return { url: call[0] as string, init: call[1] as RequestInit }
}

function headerValue(init: RequestInit, name: string): string | null {
  return new Headers(init.headers).get(name)
}

describe('useCreateOrder — UPSERT rewire (S3.1–S3.6)', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    mockAuthState.user = MOCK_AUTH_USER
    // Default: mirror the real assembleOrderData contract (full input type —
    // obs #1740 lesson: extend declared types to match production call sites).
    mockAssembleOrderData.mockImplementation(
      (input: {
        orderId: string
        cartItems: CartItem[]
        subtotal: number
        shipping: number
        total: number
        paymentIntent: PaymentIntent
      }) => ({
        orderId: input.orderId,
        items: input.cartItems,
        subtotal: input.subtotal,
        shipping: input.shipping,
        total: input.total,
        orderStatus: 'PAID',
        paymentIntentId: input.paymentIntent.id,
        paymentInfo: EXPECTED_PAYMENT_INFO,
      })
    )
    // Default fetch returns the real 200 success envelope.
    global.fetch = vi
      .fn()
      .mockResolvedValue(mockUpsertResponse(200, makeUpsertSuccessEnvelope()))
  })

  it('S3.1 — sends PUT to the by-order-id proxy with UUIDv4 X-Trace-Id and same-origin credentials', async () => {
    const { result } = renderHook(() => useCreateOrder())

    await act(async () => {
      await result.current.createOrder(
        paymentIntent,
        cartItems,
        'ORD-SERVER-1'
      )
    })

    const fetch = fetchMock()
    expect(fetch).toHaveBeenCalledTimes(1)
    const { url, init } = lastFetchCall(fetch)
    expect(init.method).toBe('PUT')
    expect(url).toBe('/api/orders/by-order-id/ORD-SERVER-1')
    expect(headerValue(init, 'X-Trace-Id')).toMatch(UUID_V4)
    expect(headerValue(init, 'Content-Type')).toBe('application/json')
    expect(init.credentials).toBe('same-origin')
  })

  it('A-12 — wire body is the D-lock subset with userId and WITHOUT orderId/orderStatus/total', async () => {
    const { result } = renderHook(() => useCreateOrder())

    await act(async () => {
      await result.current.createOrder(
        paymentIntent,
        cartItems,
        'ORD-SERVER-2'
      )
    })

    const { init } = lastFetchCall(fetchMock())
    const body = JSON.parse(init.body as string)
    expect(body).toEqual({
      userId: MOCK_AUTH_USER.id,
      paymentIntentId: paymentIntent.id,
      items: cartItems,
      subtotal: EXPECTED_SUBTOTAL,
      shipping: EXPECTED_SHIPPING,
      paymentInfo: EXPECTED_PAYMENT_INFO,
    })
    // Exact key set — proves nothing extra (orderId/orderStatus/total) leaks.
    expect(Object.keys(body).sort()).toEqual([
      'items',
      'paymentInfo',
      'paymentIntentId',
      'shipping',
      'subtotal',
      'userId',
    ])
  })

  it('A-12 — userId tracks the authenticated user from AuthContext', async () => {
    mockAuthState.user = makeAuthUser({ id: 777 })
    const { result } = renderHook(() => useCreateOrder())

    await act(async () => {
      await result.current.createOrder(
        paymentIntent,
        cartItems,
        'ORD-SERVER-3'
      )
    })

    const { init } = lastFetchCall(fetchMock())
    expect(JSON.parse(init.body as string).userId).toBe(777)
  })

  it('A-12 — user null: no fetch, friendly support fallback carrying paymentIntentId, no throw', async () => {
    mockAuthState.user = null
    const { result } = renderHook(() => useCreateOrder())

    await act(async () => {
      await result.current.createOrder(
        paymentIntent,
        cartItems,
        'ORD-SERVER-4'
      )
    })

    expect(fetchMock()).not.toHaveBeenCalled()
    expect(result.current.orderError).toBe(
      'Tu pago fue procesado, pero hubo un problema al registrar tu pedido. ' +
        'Por favor, contacta con soporte indicando tu ID de pago: pi_test_123'
    )
    expect(result.current.isCreatingOrder).toBe(false)
  })

  it('S3.2 — 200 clears the cart and invokes onSuccess with the server orderId', async () => {
    const onSuccess = vi.fn()
    const clearCart = vi.fn()
    const { result } = renderHook(() => useCreateOrder({ onSuccess, clearCart }))

    await act(async () => {
      await result.current.createOrder(
        paymentIntent,
        cartItems,
        'ORD-SERVER-5'
      )
    })

    expect(clearCart).toHaveBeenCalledTimes(1)
    expect(onSuccess).toHaveBeenCalledTimes(1)
    expect(onSuccess).toHaveBeenCalledWith('ORD-SERVER-5')
    expect(result.current.orderError).toBeNull()
    expect(result.current.isCreatingOrder).toBe(false)
  })

  it('S3.2 — 200 without onSuccess navigates to the order-confirmation page', async () => {
    const { result } = renderHook(() => useCreateOrder())

    await act(async () => {
      await result.current.createOrder(
        paymentIntent,
        cartItems,
        'ORD-SERVER-6'
      )
    })

    expect(mockPush).toHaveBeenCalledWith(
      '/order-confirmation?orderId=ORD-SERVER-6'
    )
  })

  it('S3.3 — 400 maps to the exact Spanish items copy; raw code/English never surfaces', async () => {
    global.fetch = vi
      .fn()
      .mockResolvedValue(mockUpsertResponse(400, UPSERT_ERROR_400_ITEMS))
    const onSuccess = vi.fn()
    const clearCart = vi.fn()
    const { result } = renderHook(() => useCreateOrder({ onSuccess, clearCart }))

    await act(async () => {
      await result.current.createOrder(
        paymentIntent,
        cartItems,
        'ORD-SERVER-7'
      )
    })

    expect(result.current.orderError).toBe(
      'Tu pedido no incluye productos válidos. Revisa tu carrito e inténtalo de nuevo.'
    )
    expect(result.current.orderError).not.toContain('items must be an array')
    expect(result.current.orderError).not.toContain('BadRequestError')
    // Failed persistence must not clear the cart or fire navigation.
    expect(clearCart).not.toHaveBeenCalled()
    expect(onSuccess).not.toHaveBeenCalled()
  })

  it('S3.4 — 403 maps verbatim to the ownership copy without echoing identifiers', async () => {
    global.fetch = vi
      .fn()
      .mockResolvedValue(mockUpsertResponse(403, UPSERT_ERROR_403_OWNERSHIP))
    const { result } = renderHook(() => useCreateOrder())

    await act(async () => {
      await result.current.createOrder(
        paymentIntent,
        cartItems,
        'ORD-SERVER-8'
      )
    })

    expect(result.current.orderError).toBe(
      checkoutOrderErrors(403, UPSERT_ERROR_403_OWNERSHIP, {
        paymentIntentId: paymentIntent.id,
      })
    )
    expect(result.current.orderError).not.toContain(
      'You can only modify your own orders'
    )
    expect(result.current.orderError).not.toContain(String(MOCK_AUTH_USER.id))
  })

  it('S3.5 — 409 maps verbatim to the reconciliation copy and the client NEVER retries', async () => {
    global.fetch = vi
      .fn()
      .mockResolvedValue(mockUpsertResponse(409, UPSERT_ERROR_409_GENERIC))
    const clearCart = vi.fn()
    const { result } = renderHook(() => useCreateOrder({ clearCart }))

    await act(async () => {
      await result.current.createOrder(
        paymentIntent,
        cartItems,
        'ORD-SERVER-9'
      )
    })

    // A-7: exactly one PUT for a terminal 409 — no replay, no retry loop.
    expect(fetchMock()).toHaveBeenCalledTimes(1)
    expect(result.current.orderError).toBe(
      checkoutOrderErrors(409, UPSERT_ERROR_409_GENERIC, {
        paymentIntentId: paymentIntent.id,
      })
    )
    expect(result.current.orderError).toContain('revisa Mis Pedidos')
    expect(result.current.orderError).toContain(paymentIntent.id)
    expect(clearCart).not.toHaveBeenCalled()
  })

  it('S3.6 — unknown status 500 keeps the paymentIntentId support copy', async () => {
    const envelope500 = makeUpsertErrorEnvelope(
      500,
      'InternalServerError',
      'Internal server error'
    )
    global.fetch = vi
      .fn()
      .mockResolvedValue(mockUpsertResponse(500, envelope500))
    const { result } = renderHook(() => useCreateOrder())

    await act(async () => {
      await result.current.createOrder(
        paymentIntent,
        cartItems,
        'ORD-SERVER-10'
      )
    })

    expect(result.current.orderError).toBe(
      'Tu pago fue procesado, pero hubo un problema al registrar tu pedido. ' +
        'Por favor, contacta con soporte indicando tu ID de pago: pi_test_123'
    )
    expect(result.current.orderError).not.toContain('InternalServerError')
  })

  it('S3.6 — 502 transport envelope maps to the support fallback, not a collapse', async () => {
    // Literal mirroring of upsertOrderService.synthesizeBadGateway (obs #1793
    // 502 shape — the fixture factory locks only the 400/403/409/500 set).
    const envelope502 = {
      data: null,
      error: {
        status: 502,
        name: 'BadGatewayError',
        message: 'No pudimos contactar al servidor. Inténtalo de nuevo.',
        details: { traceId: MOCK_TRACE_ID },
      },
    }
    global.fetch = vi
      .fn()
      .mockResolvedValue(mockUpsertResponse(502, envelope502))
    const { result } = renderHook(() => useCreateOrder())

    await act(async () => {
      await result.current.createOrder(
        paymentIntent,
        cartItems,
        'ORD-SERVER-11'
      )
    })

    expect(result.current.orderError).toContain(
      'contacta con soporte indicando tu ID de pago: pi_test_123'
    )
    expect(result.current.orderError).not.toContain('BadGatewayError')
  })

  it('S3.6 — fetch rejection (network down) maps to the support copy without throwing', async () => {
    global.fetch = vi.fn().mockRejectedValue(new TypeError('NetworkError'))
    const onSuccess = vi.fn()
    const { result } = renderHook(() => useCreateOrder({ onSuccess }))

    await act(async () => {
      await result.current.createOrder(
        paymentIntent,
        cartItems,
        'ORD-SERVER-12'
      )
    })

    expect(onSuccess).not.toHaveBeenCalled()
    expect(result.current.orderError).toContain(
      'contacta con soporte indicando tu ID de pago: pi_test_123'
    )
    expect(result.current.isCreatingOrder).toBe(false)
  })

  it('A-4 — each attempt generates a fresh X-Trace-Id', async () => {
    global.fetch = vi
      .fn()
      .mockResolvedValue(mockUpsertResponse(409, UPSERT_ERROR_409_GENERIC))
    const { result } = renderHook(() => useCreateOrder())

    await act(async () => {
      await result.current.createOrder(paymentIntent, cartItems, 'ORD-A')
    })
    await act(async () => {
      await result.current.createOrder(paymentIntent, cartItems, 'ORD-A')
    })

    const fetch = fetchMock()
    expect(fetch).toHaveBeenCalledTimes(2)
    const trace1 = headerValue(fetch.mock.calls[0][1] as RequestInit, 'X-Trace-Id')
    const trace2 = headerValue(fetch.mock.calls[1][1] as RequestInit, 'X-Trace-Id')
    expect(trace1).toMatch(UUID_V4)
    expect(trace2).toMatch(UUID_V4)
    expect(trace1).not.toBe(trace2)
  })

  it('S-MOD.6 — a later success clears the single orderError channel (no second banner)', async () => {
    global.fetch = vi
      .fn()
      .mockResolvedValueOnce(mockUpsertResponse(400, UPSERT_ERROR_400_ITEMS))
      .mockResolvedValueOnce(mockUpsertResponse(200, makeUpsertSuccessEnvelope()))
    const { result } = renderHook(() => useCreateOrder())

    await act(async () => {
      await result.current.createOrder(paymentIntent, cartItems, 'ORD-E')
    })
    expect(typeof result.current.orderError).toBe('string')

    await act(async () => {
      await result.current.createOrder(paymentIntent, cartItems, 'ORD-E')
    })
    expect(result.current.orderError).toBeNull()
  })
})

describe('useCreateOrder — server orderId passthrough (legacy invariants)', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    mockAuthState.user = MOCK_AUTH_USER
    mockAssembleOrderData.mockImplementation(
      (input: {
        orderId: string
        cartItems: CartItem[]
        subtotal: number
        shipping: number
        total: number
        paymentIntent: PaymentIntent
      }) => ({
        orderId: input.orderId,
        items: input.cartItems,
        subtotal: input.subtotal,
        shipping: input.shipping,
        total: input.total,
        orderStatus: 'PAID',
        paymentIntentId: input.paymentIntent.id,
        paymentInfo: EXPECTED_PAYMENT_INFO,
      })
    )
    global.fetch = vi
      .fn()
      .mockResolvedValue(mockUpsertResponse(200, makeUpsertSuccessEnvelope()))
  })

  it('passes the supplied orderId verbatim to assembleOrderData', async () => {
    const { result } = renderHook(() => useCreateOrder())

    await act(async () => {
      await result.current.createOrder(
        paymentIntent,
        cartItems,
        'ORD-SERVER-123'
      )
    })

    expect(mockAssembleOrderData).toHaveBeenCalledTimes(1)
    const call = mockAssembleOrderData.mock.calls[0][0]
    expect(call.orderId).toBe('ORD-SERVER-123')
  })
})
